version: "3.9"

services:
  proxy:
    image: nginx:1.21.4
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"

  app1:
    image: vabene1111/recipes:1.0.3
    environment:
      - GUNICORN_MEDIA=1
      - REVERSE_PROXY_AUTH=1

  app2:
    image: fireflyiii/core:version-5.6.9
    environment:
      - APP_KEY=NtrY8ftJgwdt4OC8dNVEtRoNxFVS8PeA
      - DB_CONNECTION=sqlite
      - AUTHENTICATION_GUARD=remote_user_guard
      - APP_URL=http://app2.localhost
      - TRUSTED_PROXIES=**
