version: "3.9"

services:
  proxy:
    image: nginx:1.21.4
    volumes:
    - ./default.conf.template:/etc/nginx/templates/default.conf.template
    - ./auth.conf:/config/nginx/auth.conf
    - ./oauth_endpoint.conf:/config/nginx/oauth_endpoint.conf
    - ./proxy.conf:/config/nginx/proxy.conf
    ports:
    - "80:80"

  oidc-provider:
    image: qlik/simple-oidc-provider:0.2.5
    healthcheck:
      test: wget -nv -t1 --spider 'http://127.0.0.1:9000/.well-known/openid-configuration' || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - CONFIG_FILE=/etc/config.json
      - USERS_FILE=/etc/users.json
    volumes:
      - ./oidc-config:/etc/config.json:ro
      - ./users.json:/etc/users.json:ro

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    depends_on:
      oidc-provider:
        condition: service_healthy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://auth.apps.localhost/
      - OAUTH2_PROXY_CLIENT_ID=oauth2-proxy
      - OAUTH2_PROXY_CLIENT_SECRET=secret
      - OAUTH2_PROXY_REDIRECT_URL=http://oauth2.apps.localhost/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_EXPIRE=168h0m0s
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_COOKIE_REFRESH=0
      - OAUTH2_PROXY_COOKIE_DOMAINS=.apps.localhost
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.localhost
      - OAUTH2_PROXY_COOKIE_SECRET=abcdefghiklmnlop
      - OAUTH2_PROXY_EMAIL_DOMAINS=localhost.com
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
    extra_hosts:
      - "auth.apps.localhost:172.17.0.1"

  app1:
    image: vabene1111/recipes:1.0.3
    environment:
      - GUNICORN_MEDIA=1

  app2:
    image: morganridel/mock-oidc-client:0.0.1
    environment:
      - ISSUER_BASE_URL=http://auth.apps.localhost
      - BASE_URL=http://app2.apps.localhost/api
      - CLIENT_ID=oof
      - CLIENT_SECRET=rab
      - SECRET=random-string-a5t8df86s
    extra_hosts:
      - "auth.apps.localhost:172.17.0.1"
